name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e 
            
            export PATH="/root/.nvm/versions/node/v22.14.0/bin:$PATH"

            cd /home/light2u.com.ua

            git pull origin main

            /root/.nvm/versions/node/v22.14.0/bin/bun install --silent

            /root/.nvm/versions/node/v22.14.0/bin/bun run build

            /root/.nvm/versions/node/v22.14.0/bin/pm2 restart light2u-app
          EOF
